- name: groupadd a
  tags: user
  group: name=a gid=1337 state=present

- name: useradd a
  tags: user
  user: >
    name=a
    comment='Alan Post'
    group=a
    groups="adm, sudo"
    shell=/bin/ksh
    state=present
    uid=1337

- name: add a's ssh keys
  tags: user
  authorized_key: >
    user=a
    key="{{ lookup('file', 'ssh/{{ item.file }}') }}"
    state=present
  with_items:
    - { file: 'a-20171001.pub' }

#- name: revoke a's ssh keys
#  tags: user
#  authorized_key: >
#    user=a
#    key=ssh/{{ item.file }}
#    state=absent
#  with_items:
#    - { file: 'a-20171001.pub' }

- name: cp dot,a ~a
  template: >
    src=dot,a/{{ item.file }}
    dest="~a/.{{ item.file }}"
    owner=a
    group=a
    mode={{ item.mode }}
  with_items:
    - { file: 'bashrc',        mode: '0640' }
    - { file: 'dcrc',          mode: '0640' }
    - { file: 'exrc',          mode: '0640' }
    - { file: 'inputrc',       mode: '0640' }
    - { file: 'kshrc',         mode: '0640' }
    - { file: 'nexrc',         mode: '0640' }
    - { file: 'profile',       mode: '0640' }
    - { file: 'tmux.conf',     mode: '0640' }
    - { file: 'vimrc',         mode: '0640' }

- name: rm dot,a ~a/
  file: >
    dest="~a/.{{ item.file }}"
    state=absent
  with_items:
    - { file: 'bash_logout',   mode: '0640' }
    - { file: 'bash_profile',  mode: '0640' }
