---
required_packages:
  - notqmail
  - sopel

sopel:
  nickname: mockturtle
  owner: alynpost
  username: "{{ sopel_username }}"
  password: "{{ sopel_password }}"
  admins:
    - aleph-
    - c3553eb
    - pushcx
  channels:
    - "#lobsters"
    - "#lobsters-feed"
    - "##mockturtle"
  modules:
    - clock
    - find
    - invite
    - irker
    - peterson
    - quadrille
    - safety
    - salute
    - search
    - seen
    - systemd
    - tell
    - uptime
    - url
    - wikipedia
    - wiktionary
    - xkcd
    - zoidberg
