---
- include_tasks: apt.yml

- name: Checkout bot source code    
  git:
    repo: 'https://github.com/lobsters/lobstersbot.git'
    dest: /srv/lobstersbot/
    clone: yes
    update: yes
    version: mockturtlejs
    
- name: Run install command
  command: npm install
  args:
    chdir: /srv/lobstersbot/

- name: copy bot systemd service config
  template: >
    src="unit.j2"
    dest="/etc/systemd/system/lobstersbot.service"
    owner=root
    group=root
    mode="0644"

- name: just force systemd to reread configs
  systemd: >
    name="lobstersbot"
    enabled=yes
    daemon_reload=yes
