- include_tasks: apt.yml
  when: "'{{ family }}' == 'debian'"
- include_tasks: yum.yml
  when: "'{{ family }}' == 'redhat'"

- name: copy up unicorn config
  copy: >
    src="unicorn.conf.rb"
    dest="/srv/lobste.rs/http/config"
    owner=lobsters
    group=lobsters
    mode="0644"

- name: copy unicorn systemd service config
  copy: >
    src="lobsters-unicorn.service"
    dest="/etc/systemd/system/"
    owner=lobsters
    group=lobsters
    mode="0440"

- name: just force systemd to reread configs
  systemd: >
    name="lobsters-unicorn"
    enabled=yes
    daemon_reload=yes
